# Generated by Django 5.1.1 on 2024-09-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_at_user_date_of_birth_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Kt1yjaLo2sPpVAbWULWFMs$9w4ECL1LfNrv8JJ+UhY508xDgB0rSBwirZBP+Qp8CVU=', max_length=128),
        ),
        migrations.CreateModel(
            name='UserInvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=False)),
                ('can_crud', models.BooleanField(default=False)),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investmentaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='users',
            field=models.ManyToManyField(through='api.UserInvestmentAccount', to='api.user'),
        ),
    ]
