# Generated by Django 5.1.1 on 2024-09-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_investmentaccount_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$jiO0iornD075st2dgGg1b1$Q/OZ+AjZTGxHg/xfQuKrlcSHH4RunNXXAssLRdg3MaE=', max_length=128),
        ),
    ]
