# Generated by Django 5.1.1 on 2024-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$rq2TypLrS3vdmArcIqEkzl$bHdOC/5qdm0q5AN81v84pEF6fmyXWW4w7ppunaQ2S+k=', max_length=128),
        ),
    ]
