# Generated by Django 5.1.1 on 2024-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_name_remove_user_password_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place_of_work',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
